name: Java CI with Maven and Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  qodana:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8']
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}